#! /usr/bin/env bash
# Options.
DATADIR="/znc-data"

# Make sure $DATADIR is owned by znc user. This effects ownership of the
# mounted directory on the host machine too.
chown -R znc:znc "$DATADIR"

#copy modules from src to data dir
cp -Rf /src/modules $DATADIR/

# Build modules from source.
if [ -d "${DATADIR}/modules" ]; then
  # Store current directory.
  cwd="$(pwd)"

  # Find module sources.
  modules=$(find "${DATADIR}/modules" -name "*.cpp")

  # Build modules.
  for module in $modules; do
    cd "$(dirname "$module")"
    znc-buildmod "$module"
#    make install
  done

  # Go back to original directory.
  cd "$cwd"
fi

#copy config files from src to data dir
cp -Rf /src/configs $DATADIR/

# Create default config if it doesn't exist
if [ ! -f "${DATADIR}/configs/znc.conf" ]; then
  mkdir -p "${DATADIR}/configs"
  cp /src/znc.conf.default "${DATADIR}/configs/znc.conf"
fi

# Make sure $DATADIR is owned by znc user. This effects ownership of the
# mounted directory on the host machine too.
chown -R znc:znc "$DATADIR"

# Unfortunately we can't make a pem file without user interaction, hmmm
sudo -u znc znc --makepem --foreground --datadir="$DATADIR" $@

# Start ZNC.
exec sudo -u znc znc --foreground --datadir="$DATADIR" $@
